name: RocketMQ
driverClass: io.openchaos.driver.rocketmq.RocketMQDriver

endToEndLatencyCheck: true

# RocketMQ cluster configuration

# Nodes for broker
# if the app is statefulSet , use <statefulset_name>-<ordinal>.<headless_service_name>.<namespace>.svc.cluster.local
nodes:
  - ${app}-broker-0.${app}-broker.${ns}.svc.cluster.local
  - ${app}-broker-1.${app}-broker.${ns}.svc.cluster.local

# Nodes for nameserver
# <Pod-name>.<namespace>.pod.cluster.local
metaNodes:
  - ${app}-nameserver.${ns}.svc.cluster.local

# RocketMQ configuration
rocketmqVersion: 5.2.0
installDir: /home/rocketmq/rocketmq-5.2.0 # you could set existent location for RocketMQ
nameServerPort: 9876

# RocketMQ client configuration
clusterName: DefaultCluster # same value as the config in broker.properties
vipChannelEnabled: false

# RocketMQ broker configuration
brokerClusterName: DefaultCluster
brokerName: rocketmq-broker-0
storePathRootDir: /home/rocketmq/store
storePathCommitLog: /home/rocketmq/store/commitlog
enableDLegerCommitLog: false
