name: Deploy rocketmq

on:
  push:
    branches: main

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
  DOCKER_REPO: registry.cn-guangzhou.aliyuncs.com/cc-aliyun/rocketmq-ci

jobs:
  deploy:
    if: ${{ success() }}
    name: Deploy RocketMQ
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        version: [develop-daecb087-f039-440a-87fc-5fd3d5bb34f6-ubuntu]
    steps:
      - uses: chi3316/rocketmq-test-tool@44a9a6239a5f3f194fe918accd5a41662d9fc5d1
        name: Deploy rocketmq
        with:
          action: "deploy"
          ask-config: "${{ secrets.ASK_CONFIG_VIRGINA }}"
          test-version: "${{ matrix.version }}"
          chart-git: "https://mirror.ghproxy.com/https://github.com/chi3316/rocketmq-docker"
          chart-branch: "fix-e2e"
          chart-path: "./rocketmq-k8s-helm"
          job-id: ${{ strategy.job-index }}
          helm-values: |
            nameserver:
              image:
                repository: ${{env.DOCKER_REPO}}
                tag: ${{ matrix.version }}
            broker:
              image:
                repository: ${{env.DOCKER_REPO}}
                tag: ${{ matrix.version }}
            proxy:
              image:
                repository: ${{env.DOCKER_REPO}}
                tag: ${{ matrix.version }}

# ture : 
# develop-94402c3e-906d-40ab-9161-7418164df551-ubuntu

# false : 
# develop-685d5fc4-1e2d-4bfb-8b85-ec47522d6d3c-ubuntu
# develop-4d30fa42-47cc-4f9f-ab52-cf33765efc96-ubuntu
# develop-a6f9d60d-e947-4549-a9b6-38e2c15cd69e-ubuntu
# develop-621ebe12-afcf-4a9b-8fe7-4f5a5a3d905d-ubuntu 