name: Retry Failed Job

on:
    push:
        branches:
            - "main"

jobs:
    a-successful-job:
        runs-on: ubuntu-latest
        steps:
            - name: This step can passed succesfully
              run: sleep 10 && echo "Hello World!"
    some-other-job:
        runs-on: ubuntu-latest
        steps:
            - name: This step might fail
              run: sleep 10 && exit 1

    retry-on-failure:
        needs: some-other-job
        if: always() && needs.some-other-job.result == 'failure' 
        runs-on: ubuntu-latest
        steps:
            - name: Retry the failed job
              env:
                GH_REPO: ${{ github.repository }}
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
              run: |
                  gh run rerun ${{ github.run_id }}