name: Feature Branch - Push

on:
    push:
        branches:
            - "main"
permissions:
  actions: write
  contents: write
jobs:
    some-other-step:
        runs-on: ubuntu-latest
        steps:
            - name: This step always fails
              run: sleep 20

    retry-on-failure:
        if: needs.some-other-step.result == 'failure' && fromJSON(github.run_attempt) < 4
        needs: [some-other-step]
        runs-on: ubuntu-latest
        steps:
            - env:
                  GH_REPO: ${{ github.repository }}
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: | 
                echo ${{github.run_attempt}}
                gh workflow run retry-workflow.yml -F run_id=${{ github.run_id }}