name: Test chaos-test
on:
  push:
    branches:
      - main

env:
  DOCKER_REPO: registry.cn-guangzhou.aliyuncs.com/cc-aliyun/rocketmq-ssh

jobs:
  config-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Load configuration from files
        run: |
          echo "OPENCHAOS_DRIVER=$(cat .github/chaos-configs/rocketmq.yaml)" >> $GITHUB_ENV
          echo "FAULE_FILE=$(cat .github/chaos-configs/network-delay.yaml)" >> $GITHUB_ENV
      - uses: chi3316/rocketmq-test-tool@174c23c1b1950665a6219a1d632d4468e069b45a
        name: Chaos test
        with:
          action: "test-config"
          ask-config: "${{ secrets.ACK_CONFIG_VIRGINA }}"
          job-id: ${{ strategy.job-index }}
          openchaos-driver: "${{ env.OPENCHAOS_DRIVER }}"
          chaos-mesh-fault-file: "${{ env.FAULE_FILE }}"
