name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 121.40.58.25 >> ~/.ssh/known_hosts

      - name: Start SSH tunnel to jump server
        run: |
          nohup ssh -f -N -L 6443:10.0.0.223:6443 root@121.40.58.25 &
          sleep 5
      - name: Configure kubectl
        run: |
          mkdir $HOME/.kube
          echo "${{ secrets.ACK_CONF_INNER }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
      - name: Test kubectl
        run: kubectl get nodes
