name: Test cron
on:
  push:
    branches:
      - fix-cron
jobs:
  test-cron:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: chi3316/rocketmq-test-tool@6d54a9e493d009a50663deb8df57e442bd19d81d
        name: Chaos test
        with:
          action: "cron-test"
          ask-config: "${{ secrets.ACK_CONFIG_VIRGINA }}"
      - run: pwd
      - run: ls
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: cron-log
          path: test_script.log
