name: Test chaos-test
on:
  push:
    branches:
      - test-config

jobs:
  config-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: chi3316/rocketmq-test-tool@0e2d1e085dc2449f8dd9b1b1286c7aa9437af21d
        name: test config
        with:
          action: "test-config"
          ask-config: "${{ secrets.ACK_CONFIG_VIRGINA }}"
          job-id: ${{ strategy.job-index }}
          openchaos-driver: ".github/chaos-configs/rocketmq.yaml"
          chaos-mesh-fault-file: ".github/chaos-configs/network-delay.yaml"
