name: Feature Branch - Push

on:
    push:
        branches:
            - "main"

jobs:
    some-other-step:
        runs-on: ubuntu-latest
        steps:
            - name: This step always fails
              run: sleep 10 && exit 1

    retry-on-failure:
        if: failure() && fromJSON(github.run_attempt) < 3
        needs: [some-other-step]
        runs-on: ubuntu-latest
        steps:
            - env:
                  GH_REPO: ${{ github.repository }}
                  GH_TOKEN: ${{ github.token }}
              run: | 
                echo ${{github.run_attempt}}
                gh workflow run "${{ github.workflow }}" -F run_id="${{ github.run_id }}"