name: Test chaos-test
on:
  push:
    branches:
      - main

env:
  DOCKER_REPO: registry.cn-guangzhou.aliyuncs.com/cc-aliyun/rocketmq-ssh

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        version: [v2.3]
    steps:
      - uses: chi3316/rocketmq-test-tool/chaos-test-runner@fbbcdcb8c3d9bdf2c2a5c64585b648cf2f183cac
        name: Deploy rocketmq
        with:
          action: "deploy"
          ask-config: "${{ secrets.ASK_CONFIG_VIRGINA }}"
          test-version: "v0.1"
          chart-git: "https://mirror.ghproxy.com/https://github.com/chi3316/rocketmq-docker"
          chart-branch: "chaos-test"
          chart-path: "./rocketmq-k8s-helm"
          job-id: ${{ strategy.job-index }}
          helm-values: |
            nameserver:
              image:
                repository: ${{env.DOCKER_REPO}}
                tag: ${{ matrix.version }}
            broker:
              image:
                repository: ${{env.DOCKER_REPO}}
                tag: ${{ matrix.version }}
            proxy:
              image:
                repository: ${{env.DOCKER_REPO}}
                tag: ${{ matrix.version }}

  chaos-test:
    runs-on: ubuntu-latest
    needs: deploy
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: chi3316/rocketmq-test-tool/chaos-test-runner@fbbcdcb8c3d9bdf2c2a5c64585b648cf2f183cac
        name: Chaos test
        with:
          action: "chaos-test"
          ask-config: "${{ secrets.ASK_CONFIG_VIRGINA }}"
          job-id: ${{ strategy.job-index }}
          openchaos-driver: ".github/chaos-configs/driver.yaml"
          chaos-mesh-fault-file: ".github/chaos-configs/network-delay.yaml"
          fault-scheduler-interval: "30"
          openchaos-args: "-t 240"
          fault-durition: "30"
          node-lable: "app.kubernetes.io/name=broker"
          meta-node-lable: "app.kubernetes.io/name=nameserver"
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: chaos-test-report
          path: chaos-test-report/
        if: always()
  clean:
    if: always()
    name: Clean
    needs: [deploy, chaos-test]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: chi3316/rocketmq-test-tool/chaos-test-runner@fbbcdcb8c3d9bdf2c2a5c64585b648cf2f183cac
        name: clean
        with:
          action: "clean"
          ask-config: "${{ secrets.ASK_CONFIG_VIRGINA }}"
          job-id: ${{ strategy.job-index }}
