name: Test K8s Config

on:
    push:
        branches:
            - main

env:
    SECRET: $(echo "${{ secrets.ASK_CONFIG_VIRGINA }}" | base64 -w 0)

jobs:
    test-config:
        runs-on: ubuntu-latest
        steps:
            - name: Install kubectl
              run: |
                curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
                sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

            - name: Config K8s
              run: |
                # encoded_value=$(echo "${{ secrets.ASK_CONFIG_VIRGINA }}" | base64 -w 0)
                mkdir -p ${HOME}/.kube
                
                secret=${{ env.SECRET }}
                kube_config=$(echo $secret | base64 -d)
                echo "${kube_config}" > ${HOME}/.kube/config

            - name: Check connection
              run: kubectl get nodes
