name: Test chaos-test
on:
  push:
    branches:
      - main

env:
  DOCKER_REPO: registry.cn-guangzhou.aliyuncs.com/cc-aliyun/rocketmq-ssh

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        version: [v2.2]
    steps:
      - uses: chi3316/rocketmq-test-tool@f68a5d3b36be2395ab007edbe8a1c506f80ef5f1
        name: Deploy rocketmq
        with:
          action: "deploy"
          ask-config: "${{ secrets.ACK_CONFIG_VIRGINA }}"
          test-version: "v0.1"
          chart-git: "https://ghproxy.com/https://github.com/apache/rocketmq-docker.git"
          chart-branch: "master"
          chart-path: "./rocketmq-k8s-helm"
          job-id: ${{ strategy.job-index }}
          helm-values: |
            nameserver:
              image:
                repository: ${{env.DOCKER_REPO}}
                tag: ${{ matrix.version }}
            broker:
              image:
                repository: ${{env.DOCKER_REPO}}
                tag: ${{ matrix.version }}
            proxy:
              image:
                repository: ${{env.DOCKER_REPO}}
                tag: ${{ matrix.version }}

  chaos-test:
    runs-on: ubuntu-latest
    needs: deploy
    timeout-minutes: 10
    steps:
      - uses: chi3316/rocketmq-test-tool@90e314d3b405c9c945cbe5071504edb14a5ddff7
        name: Chaos test
        with:
          action: "chaos-test"
          ask-config: "${{ secrets.ACK_CONFIG_VIRGINA }}"
          job-id: ${{ strategy.job-index }}
      - run: pwd
      - run: ls
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: chaos-test-report
          path: chaos-test-report/
  clean:
    if: always()
    name: Clean
    needs: [deploy, chaos-test]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: chi3316/rocketmq-test-tool@90e314d3b405c9c945cbe5071504edb14a5ddff7
        name: clean
        with:
          action: "clean"
          ask-config: "${{ secrets.ACK_CONFIG_VIRGINA }}"
          job-id: ${{ strategy.job-index }}
