name: Upload test logs

on:
    push:
        branches:
            - "your-branch"

jobs:
    a-test-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2