name: Test chaos-test
on:
  push:
    branches:
      - main

env:
  DOCKER_REPO: registry.cn-guangzhou.aliyuncs.com/cc-aliyun/rocketmq-ssh

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        version: [v2.2]
    steps:
      - uses: chi3316/rocketmq-test-tool@67b1759c68c488ce66fd34d41e0010eee21ec65e
        name: Deploy rocketmq
        with:
          action: "deploy"
          ask-config: "${{ secrets.ACK_CONFIG_VIRGINA }}"
          test-version: "v0.1"
          chart-git: "https://ghproxy.com/https://github.com/apache/rocketmq-docker.git"
          chart-branch: "master"
          chart-path: "./rocketmq-k8s-helm"
          job-id: ${{ strategy.job-index }}
          helm-values: |
            nameserver:
              image:
                repository: ${{env.DOCKER_REPO}}
                tag: ${{ matrix.version }}
            broker:
              image:
                repository: ${{env.DOCKER_REPO}}
                tag: ${{ matrix.version }}
            proxy:
              image:
                repository: ${{env.DOCKER_REPO}}
                tag: ${{ matrix.version }}

  chaos-test:
    runs-on: ubuntu-latest
    needs: deploy
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: chi3316/rocketmq-test-tool@65d2f71470c409475aeff755fdffc2c2b86b6afd
        name: Chaos test
        with:
          action: "chaos-test"
          ask-config: "${{ secrets.ACK_CONFIG_VIRGINA }}"
          job-id: ${{ strategy.job-index }}
          openchaos-driver: ".github/chaos-configs/test.yaml"
          chaos-mesh-fault-file: ".github/chaos-configs/network-delay.yaml"
          fault-scheduler-interval: "30"
          openchaos-args: "-t 240"
          fault-durition: "30"
          helm-chart-repo: "https://chi3316.github.io/my_chart/"
          helm-chart-version: "0.0.3"
          helm-chart: "rocketmq"
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: chaos-test-report
          path: chaos-test-report/
        continue-on-error: true
  clean:
    if: always()
    name: Clean
    needs: [deploy, chaos-test]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: chi3316/rocketmq-test-tool@67b1759c68c488ce66fd34d41e0010eee21ec65e
        name: clean
        with:
          action: "clean"
          ask-config: "${{ secrets.ACK_CONFIG_VIRGINA }}"
          job-id: ${{ strategy.job-index }}
