name: Feature Branch - Push

on:
    push:
        branches:
            - your-branch
permissions:
  actions: write
  contents: write
jobs:
    some-other-step:
        runs-on: ubuntu-latest
        env:
            GH_REPO: ${{ github.repository }}
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - name: This step always fails
              run: sleep 10 && exit 1
            - name: Retry if failed
              if: failure() && fromJSON(github.run_attempt) < 4
              run: |
                echo "Retrying..."
                gh workflow run retry-workflow.yml -F run_id=${{ github.run_id }}
