name: Test chaos-test
on:
  push:
    branches:
      - test-config-0

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        version: [v2.2]
    steps:
      - uses: chi3316/rocketmq-test-tool@476026f7b0c8312e38866f06e545e70a4bd93966
        name: Deploy rocketmq
        with:
          action: "deploy"
          ask-config: "${{ secrets.ACK_CONFIG_VIRGINA }}"
          test-version: "v0.1"
          chart-git: "https://ghproxy.com/https://github.com/apache/rocketmq-docker.git"
          chart-branch: "master"
          chart-path: "./rocketmq-k8s-helm"
          job-id: ${{ strategy.job-index }}

  config-test:
    runs-on: ubuntu-latest
    needs: deploy
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: chi3316/rocketmq-test-tool@9f9420e7496c636df8c6a3e8f60ae1ce88b99191
        name: test config
        with:
          action: "test-config"
          ask-config: "${{ secrets.ACK_CONFIG_VIRGINA }}"
          job-id: ${{ strategy.job-index }}
          chaos-mesh-fault-file: ".github/chaos-configs/network-delay.yaml"
          openchaos-driver: ".github/chaos-configs/rocketmq-driver.yaml"

  clean:
    if: always()
    name: Clean
    needs: [deploy, config-test]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: chi3316/rocketmq-test-tool@476026f7b0c8312e38866f06e545e70a4bd93966
        name: clean
        with:
          action: "clean"
          ask-config: "${{ secrets.ACK_CONFIG_VIRGINA }}"
          job-id: ${{ strategy.job-index }}
