name: Test chaos-test
on:
  push:
    branches:
      - main

env:
  DOCKER_REPO: registry.cn-guangzhou.aliyuncs.com/cc-aliyun/rocketmq-ssh

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        version: [v2.2]
    steps:
      - uses: chi3316/rocketmq-test-tool@2b7c6806384cd0b31da8a619e905d92155b02daa
        name: Deploy rocketmq
        with:
          action: "deploy"
          ask-config: "${{ secrets.ACK_CONFIG_VIRGINA }}"
          test-version: "v0.1"
          chart-git: "https://ghproxy.com/https://github.com/apache/rocketmq-docker.git"
          chart-branch: "master"
          chart-path: "./rocketmq-k8s-helm"
          job-id: ${{ strategy.job-index }}
          helm-values: |
            nameserver:
              image:
                repository: ${{env.DOCKER_REPO}}
                tag: ${{ matrix.version }}
            broker:
              image:
                repository: ${{env.DOCKER_REPO}}
                tag: ${{ matrix.version }}
            proxy:
              image:
                repository: ${{env.DOCKER_REPO}}
                tag: ${{ matrix.version }}
  chaos-test:
    runs-on: ubuntu-latest
    needs: deploy
    timeout-minutes: 10
    steps:
      - uses: chi3316/rocketmq-test-tool@2b7c6806384cd0b31da8a619e905d92155b02daa
        name: Chaos test
        with:
          action: "chaos-test"
          ask-config: "${{ secrets.ACK_CONFIG_VIRGINA }}"
      - name: Copy test report to working directory
        run: cp -r /root/chaos-test/report ${{ github.workspace }}/chaos-test-report
      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: chaos-test-report
          path: ${{ github.workspace }}/chaos-test-report
  clean:
    if: always()
    name: Clean
    needs: [deploy, chaos-test]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: chi3316/rocketmq-test-tool@2b7c6806384cd0b31da8a619e905d92155b02daa
        name: clean
        with:
          action: "clean"
          ask-config: "${{ secrets.ACK_CONFIG_VIRGINA }}"
          job-id: ${{ strategy.job-index }}
