name: Test chaos-test
on:
  push:
    branches:
      - test-config

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        version: [v2.2]
    steps:
      - uses: chi3316/rocketmq-test-tool@476026f7b0c8312e38866f06e545e70a4bd93966
        name: Deploy rocketmq
        with:
          action: "deploy"
          ask-config: "${{ secrets.ACK_CONFIG_VIRGINA }}"
          test-version: "v0.1"
          chart-git: "https://ghproxy.com/https://github.com/apache/rocketmq-docker.git"
          chart-branch: "master"
          chart-path: "./rocketmq-k8s-helm"
          job-id: ${{ strategy.job-index }}

  config-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: chi3316/rocketmq-test-tool@29d990c487547c498410ed09d9c52fe3c860cb12
        name: test config
        with:
          action: "test-config"
          ask-config: "${{ secrets.ACK_CONFIG_VIRGINA }}"
          job-id: ${{ strategy.job-index }}
          chaos-mesh-fault-file: ".github/chaos-configs/network-delay.yaml"
          openchaos-driver: YXBpVmVyc2lvbjogdjEKa2luZDogQ29uZmlnTWFwCm1ldGFkYXRhOgogIG5hbWU6IHJvY2tldG1xLWNvbmZpZ21hcApkYXRhOgogIHJvY2tldG1xLnlhbWw6IHwKICAgIG5hbWU6IFJvY2tldE1RCiAgICBkcml2ZXJDbGFzczogaW8ub3BlbmNoYW9zLmRyaXZlci5yb2NrZXRtcS5Sb2NrZXRNUURyaXZlcgogICAgCiAgICBlbmRUb0VuZExhdGVuY3lDaGVjazogdHJ1ZQogICAgCiAgICAjIFJvY2tldE1RIGNsdXN0ZXIgY29uZmlndXJhdGlvbgogICAgCiAgICAjIE5vZGVzIGZvciBicm9rZXIKICAgIG5vZGVzOiAKICAgIC0gcm9ja2V0bXEtYnJva2VyLTAtc3NoCiAgICAtIHJvY2tldG1xLWJyb2tlci0xLXNzaAogICAgLSByb2NrZXRtcS1icm9rZXItMi1zc2gKICAgIAogICAgIyBOb2RlcyBmb3IgbmFtZXNlcnZlcgogICAgbWV0YU5vZGVzOgogICAgLSBuYW1lc2VydmVyLXNzaAogICAgCiAgICAjIFJvY2tldE1RIGNvbmZpZ3VyYXRpb24KICAgIHJvY2tldG1xVmVyc2lvbjogNS4yLjAKICAgIGluc3RhbGxEaXI6IC9ob21lL3JvY2tldG1xL3JvY2tldG1xLTUuMi4wICMgeW91IGNvdWxkIHNldCBleGlzdGVudCBsb2NhdGlvbiBmb3IgUm9ja2V0TVEKICAgIG5hbWVTZXJ2ZXJQb3J0OiA5ODc2CiAgICAKICAgICMgUm9ja2V0TVEgY2xpZW50IGNvbmZpZ3VyYXRpb24KICAgIGNsdXN0ZXJOYW1lOiBEZWZhdWx0Q2x1c3RlciAjIHNhbWUgdmFsdWUgYXMgdGhlIGNvbmZpZyBpbiBicm9rZXIucHJvcGVydGllcwogICAgdmlwQ2hhbm5lbEVuYWJsZWQ6IGZhbHNlCiAgICAKICAgICMgUm9ja2V0TVEgYnJva2VyIGNvbmZpZ3VyYXRpb24KICAgIGJyb2tlckNsdXN0ZXJOYW1lOiBEZWZhdWx0Q2x1c3RlcgogICAgYnJva2VyTmFtZTogcm9ja2V0bXEtYnJva2VyLTAKICAgIHN0b3JlUGF0aFJvb3REaXI6IC9ob21lL3JvY2tldG1xL3N0b3JlCiAgICBzdG9yZVBhdGhDb21taXRMb2c
