name: Test chaos-test
on:
  push:
    branches:
      - main

env:
  DOCKER_REPO: registry.cn-guangzhou.aliyuncs.com/cc-aliyun/rocketmq-ssh

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        version: [2.2]
    steps:
      - uses: chi3316/rocketmq-test-tool@ceae9eaced933b1eb206fc1cc8de9a3db917a2f2
        name: Deploy rocketmq
        with:
          action: "deploy"
          ask-config: "${{ secrets.ACK_CONFIG_VIRGINA }}"
          test-version: "v0.1"
          chart-git: "https://ghproxy.com/https://github.com/apache/rocketmq-docker.git"
          chart-branch: "master"
          chart-path: "./rocketmq-k8s-helm"
          job-id: ${{ strategy.job-index }}
          helm-values: |
            nameserver:
              image:
                repository: ${{env.DOCKER_REPO}}
                tag: ${{ matrix.version }}
            broker:
              image:
                repository: ${{env.DOCKER_REPO}}
                tag: ${{ matrix.version }}
            proxy:
              image:
                repository: ${{env.DOCKER_REPO}}
                tag: ${{ matrix.version }}
  chaos-test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: chi3316/rocketmq-test-tool@ceae9eaced933b1eb206fc1cc8de9a3db917a2f2
        name: Chaos test
        with:
          action: "chaos-test"
