name: Test chaos-test
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: apache/rocketmq-test-tool@7d84d276ad7755b1dc5cf9657a7a9bff6ae6d288
        name: Deploy rocketmq
        with:
          action: "deploy"
          ask-config: "${{ secrets.ASK_CONFIG_VIRGINA }}"
          test-version: "v0.1"
          chart-git: "https://ghproxy.com/https://github.com/apache/rocketmq-docker.git"
          chart-branch: "master"
          chart-path: "./rocketmq-k8s-helm"
          job-id: ${{ strategy.job-index }}
  chaos-test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: chi3316/rocketmq-test-tool@2cc5f8269292db7667ffabe2c68d05ff0268f450
        name: Chaos test
        with:
          action: "chaos-test"
